stages:
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

test:
  stage: test
  before_script:
     - npx ci
     - npx install cypress
  script:
    - npx cypress run --browser chrome  
pages:
  stage: deploy 
  script:
    - npm generateReport
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
      - ./reports/cucumber-htmlreport.html/index.html
    expire_in: 1 day