stages:
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

test:
  stage: test
  before_script:
     - npm ci
     - npx install cypress
  script:
    - npx cypress run --browser chrome
  after_script:
    - npm generateReport
pages:  
  stage: deploy 

  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
      - ./reports/cucumber-htmlreport.html/index.html
    expire_in: 1 day