stages: 
  - testing 
  - deploy  
 
job: 
   
  script: 
    - npm run test  
  after_script: 
    - npm generateReport 
  allow_failure: true 
  artifacts:  
    when: always 
    paths: 
      - ./index.html
    expire_in: 1 day  
pages:  
  stage: deploy 
    
  artifacts: 
    paths: 
      - public 
  rules: 
    - when: always
