name: cypress test with cucumber

on:
    push:
        branches: [gh-page]

jobs:
    Run_test:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [14.17.0]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"   
            - run: npm i npm@latest
            - run: npm i
            - run: npm install cypress 
            - run: npm install @badeball/cypress-cucumber-preprocesso
            - name: run test
              run: npm run runOnChrome
      
                
